### ISSUE TITLE
Running mypy for file in directory starting with "@" fails

### ISSUE THREAD

**Issue by MikiGrit** [pre-commit/mirrors-mypy#12]
I have a problem with running mypy hook for a file inside directory starting with `@`. E.g. adding file `@somedir/script.py` to commit fails mypy with
```bash
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: [Errno 2] No such file or directory: 'somedir/script.py'
```

while adding file `script.py` commits fine. How should I do it? Is it possible?

Thanks.

**Comment by asottile** [comment]
this just calls mypy with the filenames verbatim, I'd suggest asking the upstream project
