### ISSUE TITLE
Running hook on entire project

### ISSUE THREAD

**Issue by JarnoRFB** [pre-commit/mirrors-mypy#13]
Hi, I find this hook very useful. However, it happens sometimes that one changes a file, that introduces a type error in a file that was left unchanged. Is there a way to configure the hook, such that it will always check the entire package?

**Comment by asottile** [comment]
not really -- the point of pre-commit is to be quick checks and not a catch-all (it can be partially or completely skipped after all!) -- I'd suggest you configure `pre-commit run --all-files --show-diff-on-failure` in your CI if you need something definitive
