### ISSUE TITLE
Use my-py pre-commit hook in a legacy project with hundreds of warnings

### ISSUE THREAD

**Issue by vinicius-ronconi** [pre-commit/mirrors-mypy#16]
I'm trying to introduce my-py in a legacy project with hundreds of warnings. I added the following to my `.pre-commit-config.yml`:

```
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
```

When I modify a single file, the pre-commit hook is scanning all files in the project instead of only the modified files. Is that the expected behaviour? Is there anything I can configure to warn me just about the changed files (at least while we're able to reduce the number of issues)?

**Comment by asottile** [comment]
mypy follows imports as it does dynamic analysis -- if you run `mypy somefile.py` which triggers imports that import your whole codebase then you'll see errors from those files.  note that `pre-commit` is not doing that, that's mypy

you can configure mypy to gradually enable parts of your codebase by utilizing their configuration settings (you'll essentially tell it to ignore particular packages until you can fix them)

**Comment by vinicius-ronconi** [comment]
Makes sense! Thank you @asottile !!

**Comment by vinicius-ronconi** [comment]
Just to document my solution in case someone else needs it:

For now, I'm configuring mypy with `--follow-imports silent`. It will block the commit only if the file contains an issue.

It is not ideal for the long-term since a change in one file can introduce issues in a different one. After some weeks we will re-evaluate that and probably remove this clause from our settings.
