### ISSUE TITLE
Read configuration from `setup.cfg`

### ISSUE THREAD

**Issue by tomwhite** [pre-commit/mirrors-mypy#22]
Perhaps there's a way of doing this that I missed, but I'd like `mypy` `pre-commit` to use the settings in `setup.cfg`

**Comment by asottile** [comment]
have you tried it? [it works](https://github.com/deadsnakes/runbooks/blob/9355d20f14f093fb8b5234fe35cfa5fd953e7384/setup.cfg#L1)

**Comment by tomwhite** [comment]
I tried it, but got confused by the separate virtualenv not picking up dependencies. It works fine. Apologies for the noise.

**Comment by asottile** [comment]
make sure to check [the bottom of the README](https://github.com/pre-commit/mirrors-mypy#using-mypy-with-pre-commit)
