### ISSUE TITLE
Update mypy to 0.790

### ISSUE THREAD

**Issue by cooperlees** [pre-commit/mirrors-mypy#27]
0.790 is out ... seems changes are needed here ...

If I get time I'll try and work it out.

https://github.com/pypa/bandersnatch/pull/705 would have updated mypy if I didn't use pre-commit. Instead I have this manual work to do now :(

**Comment by cooperlees** [comment]
O, looking at commit there is a github action ... can we trigger it?

**Comment by asottile** [comment]
it gets triggered on a schedule so it'll be updated within 24 hours 👍

**Comment by cooperlees** [comment]
Seems a premature close, as, it's not updated ...

**Comment by asottile** [comment]
I mean, on one hand I agree, on the other hand it will auto resolve itself and I'd rather not have to remember to come back and close this
