### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by sondrelg** [pre-commit/mirrors-mypy#37]
Hi!

This isn't meant as a nag, but as a heads up in case you hadn't seen: can you upgrade this to match the latest mypy release?

I could also create a PR if you want - is it just a matter of upgrading the `setup.py` + `.version`?

**Comment by asottile** [comment]
> This isn't meant as a nag, 

then why did you open it ?  this is 100% a nag

See also #36

**Comment by sondrelg** [comment]
> then why did you open it ?

It says right after: as a heads up in case you hadn't seen mypy released a new minor version, and this repo is no longer up to date. Only trying to help..
