### ISSUE TITLE
The way mypy is invoked by pre-commit may hide legitimate type errors

### ISSUE THREAD

**Issue by obi1kenobi** [pre-commit/mirrors-mypy#39]
The way that `pre-commit` invokes `mypy` may cause `mypy` to erroneously fail to find and report some kinds of type errors. This is related to mypy bug https://github.com/python/mypy/issues/9954 and I happened to run into it while working with the `pip` source code: https://github.com/pypa/pip/issues/9502

Specifically, the issue is that `pre-commit` invokes `mypy` with a list of files to scan. Due to what appears to me to be a bug in `mypy`, this is not equivalent to invoking `mypy` on the directory containing those files, *even though* all the files in that directory were included in the list in the original invocation. In other words, it is possible to construct a scenario where the following two invocations differ in outcomes — one will claim that there are no type errors, while the other will find valid type errors, even though both runs scanned the same files and used the same `mypy` configuration:
```
mypy src/
```
vs
```
mypy src/foo.py src/bar.py < ... all other Python files inside src/ ... >
```

This issue is causing 51 type errors to be inappropriately hidden (and not even caught in CI!) in the `pip` project. More details here: https://github.com/pypa/pip/issues/9502

I'm not sure if this is solvable within `pre-commit` or `mirrors-mypy`. I wanted to open this issue to raise awareness about the problem, since it may lead projects using `mypy` via `pre-commit` toward a false sense of security — they may falsely believe their code to be in compliance with their `mypy` configuration (and that such compliance is being enforced by CI, as in the `pip` project!) even though a different `mypy` invocation would correctly find and report type errors.

**Comment by asottile** [comment]
the bug is in mypy, not here -- please report it there

**Comment by asottile** [comment]
also it looks like from that thread it's because you configured `exclude` and disabled following imports, so this report is inaccurate and due to your misconfiguration

**Comment by obi1kenobi** [comment]
You are absolutely correct that the "actual" bug is in the user's expectations not matching what the project's `mypy` configuration says. The `pip` repo should almost certainly not use `follow_imports = skip`, and this isn't really a bug in `pre-commit` (although you might still be interested in the `mypy` maintainers' thoughts on how best to invoke `mypy` [posted here](https://github.com/python/mypy/issues/9954#issuecomment-766302123)).

The reason I opened this issue is because the way `pre-commit` uses `mypy` makes projects _non-obviously_ more susceptible to this particular and commonly-misused `mypy` setting. Specifically in `pip`'s case, this bug has been present and undetected for _4 years_, ever since `follow_imports = skip` got added in [this commit](https://github.com/pypa/pip/commit/ed9208efaffd4d93f09ef0e07b32e445d392e535). Since the `mypy` invocation in `pre-commit` isn't particularly obvious, even tracking down and reproducing the difference in outcomes took a significant amount of time.

What I had in mind when opening this issue was some sort of way to warn future users of this potential gotcha. It could take the shape of e.g. a runtime warning when `follow_imports = skip` is detected in the `mypy` configuration, or it could even be a "loud" bit of warning text in the documentation telling users to stay away from `follow_imports = skip` if using `mypy` through `pre-commit`. If I were a new user starting to use a package, I'd love to know about known sharp edges to avoid, even if they are technically because of a (widespread!) misconfiguration of another tool — avoiding the tricky and non-obvious problem would improve my user experience.

Of course, I'm not the maintainer so it's ultimately your call one way or the other. Just my 2 cents :)

**Comment by asottile** [comment]
yeah if you scroll through the many duplicate issues there's plenty explanation for why the defaults are set up the way they are, as well as directions if you want to configure it in the way the mypy maintainers (incorrectly imo for the trade offs present) suggest.  I'd encourage you to review those
