### ISSUE TITLE
Mypy hook not detecting all errors

### ISSUE THREAD

**Issue by bazylip** [pre-commit/mirrors-mypy#41]
When using latest release (0.812), mypy hook does not find all errors that are found when running `mypy` manually or through CI. It does show some of them but not all - sometimes leading to pre-commit passing all hooks and accepting a commit which later fails during `mypy` check in CI. Is this a known issue?

**Comment by asottile** [comment]
we can't see your screen

please open a new issue where you've put in the effort to make a reproducible case

also make sure to read the README for common issues, it may be your problem but it's impossible to know with such a low quality report
