### ISSUE TITLE
mypy differences when run as a "true" hook vs pre-commit run -a

### ISSUE THREAD

**Issue by Caligatio** [pre-commit/mirrors-mypy#43]
I recently ran into a problem where I think I know why it's happening but don't know how to fix it.  The repository in question is https://github.com/Caligatio/paranoid-openvpn

**The Problem**
Running `pre-commit run -a` yields no `mypy` errors yet `mypy` will throw errors when the hook is run on a `git commit` against against my unit tests.

**Probable Explanation**
I opted to structure my project with a top level `src` directory to avoid import confusion.  When `pre-commit run -a` is executed, it passes all my `src` files to `mypy` along with my tests and I believe `mypy` uses those files to satisfy the imports for my tests.  When mypy is run as a hook when only a test is changed, there's no automagic import of my library due to the `src` (which is exactly what I intended) and, because `mypy` is invoked from its own virtualenv, my module isn't available.  It therefore cannot actually import my code/typing, thus thinking my `# type: ignore`s are unneeded.

**Example Output**
```console
➜  paranoid-openvpn git:(main) pre-commit run --all-files                      
black....................................................................Passed
flake8...................................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
mypy.....................................................................Passed

➜  paranoid-openvpn git:(main) echo "# Silly" >> tests/test_profile_parsers.py 
➜  paranoid-openvpn git:(main) ✗ git add tests/test_profile_parsers.py 
➜  paranoid-openvpn git:(main) ✗ git commit -m "This will fail"
black....................................................................<OUTPUT OMITTED>
flake8...................................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

tests/test_profile_parsers.py:302: error: unused 'type: ignore' comment
tests/test_profile_parsers.py:316: error: unused 'type: ignore' comment
tests/test_profile_parsers.py:333: error: unused 'type: ignore' comment
tests/test_profile_parsers.py:347: error: unused 'type: ignore' comment
Found 4 errors in 1 file (checked 1 source file)
```

Since the import problem is the actual library under development, I don't think I can use `additional_dependencies` to somehow install itself.

Any ideas would be greatly appreciated.

**Comment by asottile** [comment]
you can use mypy's `mypy_path` to hint that you're using `src` layout:

```ini
[mypy]
mypy_path = src
```

**Comment by Caligatio** [comment]
Thank you @asottile, that worked!
