### ISSUE TITLE
License of mirrors-mypy

### ISSUE THREAD

**Issue by sbkok** [pre-commit/mirrors-mypy#44]
Thanks for making this pre-commit hook config available.
I would like to use this configuration in my setup, however I could not find the license attached to it.

Could you please update the repository to state under what license this repository is made open source?

**Comment by asottile** [comment]
the content here, minus the README, is entirely generated from https://github.com/pre-commit/pre-commit-mirror-maker/blob/master/LICENSE

**Comment by asottile** [comment]
via #45
