### ISSUE TITLE
Why setting default args?

### ISSUE THREAD

**Issue by ramnes** [pre-commit/mirrors-mypy#48]
Hey there, thanks for the awesome work on pre-commmit!

I'm just wondering why these arguments are set here by default: https://github.com/pre-commit/mirrors-mypy/blob/master/.pre-commit-hooks.yaml#L6

It introduces an inconsistency between mypy being ran with or without pre-commit, and it took me quite some time to understand.

**Comment by asottile** [comment]
the readme is short, please read it

**Comment by ramnes** [comment]
It doesn't say why, tho. :)

**Comment by asottile** [comment]
???

> By default, mypy will run with mypy --ignore-missing-imports, pre-commit runs mypy from an isolated virtualenv so it won't have access to those.

**Comment by ramnes** [comment]
Yeah, I've read that. It doesn't say why the choice was made to skip them by default, which kinda defeats the purpose of mypy, rather recommend using `additional_dependencies`.

**Comment by asottile** [comment]
I have to assume you're trolling me at this point, the readme talks about exactly that
