### ISSUE TITLE
Breaking change in mypy v0.900 bundled stubs

### ISSUE THREAD

**Issue by janosh** [pre-commit/mirrors-mypy#53]
Some of my [pre-commit.ci runs](https://results.pre-commit.ci/run/github/376834832/1625518032.cPl4jejmT9mZSZarAe5-hQ) are failing after a [breaking change in mypy v0.900](https://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html):

> Note: Even if you are using --ignore-missing-imports, mypy will ask to install stubs for packages that had bundled stubs in previous mypy releases. This helps you avoid losing type checking precision from missing stubs when upgrading to mypy 0.900.

What's the recommended fix here?

**Comment by asottile** [comment]
see: [the duplicates](https://github.com/pre-commit/mirrors-mypy/issues?q=is%3Aissue+is%3Aopen+900+is%3Aclosed) and [the README](https://github.com/pre-commit/mirrors-mypy#using-mypy-with-pre-commit)

**Comment by asottile** [comment]
you may also find [types-all](https://github.com/asottile/types-all) an easy hammer

**Comment by janosh** [comment]
My bad for not searching duplicates carefully.

I did see the readme but was hoping there's a way that avoids specifying `additional_dependencies` manually. I assume, the version of dependencies will not be auto-updated by pre-commit.ci? Do I _have_ to specify a version? Is there a `latest` keyword or something?
