### ISSUE TITLE
Pre-commit hook inadvertently checks files outside of target submodule

### ISSUE THREAD

**Issue by dannygoldstein** [pre-commit/mirrors-mypy#54]
First, thanks for making such a great tool!

On my fork of the weights and biases client repository,
https://github.com/dannygoldstein/client/tree/3e7f8d347bb03a4b87e7504f3d1fe01e064dc684

I have a submodule `wandb/sweeps` that has the `mirrors-mypy` pre-commit hook  version 0.812 installed: 
https://github.com/wandb/sweeps/tree/5051fef2671d726ed098d695308f46cca9808f0d

If I attempt to commit changes to a file in `sweeps` when the repository is checked out outside of `client` (i.e., not a submodule), everything works as expected. However, if I `cd` into the submodule `client/wandb/sweeps`, make changes to a file, and then attempt to commit those changes within the submodule, the commit hook checks files in `client/wandb`, failing with errors because the files in the containing module are not properly typed. The behavior I expected is that the pre-commit hook would only check the files changed in the commit (I am using `pass_filenames: True`). None of the files in the submodule import any of the files in the containing module, so I wouldn't expect the hook to check those. 

How to reproduce: 

- Check out the repo with submodule:
  - `git clone https://github.com/dannygoldstein/client.git`
  - `git checkout 3e7f8d347bb03a4b87e7504f3d1fe01e064dc684`
  - `git submodule update --init --remote`
- CD into the submodule
  -  cd `client/wandb/sweeps`
- Run `pre-commit install`
- Change any file 
- Attempt to commit that change
- See the mypy pre-commit hook fail

Some observations:

1. If I remove `__init__.py` from the submodule top level directory, then this issue goes away. But I can't do that in production
2. I used a debugger to find the command that `pre-commit` was running to execute my hook, it was:

```python
/Users/danielgoldstein/.cache/pre-commit/repozddjrnnf/py_env-python3.6/bin/python /Users/danielgoldstein/.cache/pre-commit/repozddjrnnf/py_env-python3.6/bin/mypy --ignore-missing-imports --scripts-are-modules params.py
```

Which produced
`Found 59 errors in 16 files (checked 1 source file)`

But the identical command with my local mypy 

```python
mypy --ignore-missing-imports --scripts-are-modules params.py
```

produces
`Success: no issues found in 1 source file`

I ran both of these commands in verbose `-vv` mode and found that the pre-commit hook version has

```
TRACE: package_path:
TRACE:     /Users/danielgoldstein/.cache/pre-commit/repozddjrnnf/py_env-python3.6/lib/python3.6/site-packages
TRACE:     /Users/danielgoldstein/.local/lib/python3.6/site-packages
```

while the second version (that produces a successful result) has

```
TRACE: package_path:
TRACE:     /Users/danielgoldstein/go/src/github.com/wandb/client
TRACE:     /Users/danielgoldstein/.pyenv/versions/3.6.8/envs/wandb-3.6/lib/python3.6/site-packages
TRACE:     /Users/danielgoldstein/.local/lib/python3.6/site-packages
```

It seems like somehow the pre-commit hook version is dropping the `/Users/danielgoldstein/go/src/github.com/wandb/client` from the package path?

**Comment by asottile** [comment]
cannot reproduce:

```console
$ pre-commit  run mypy --files params.py | tail -2
Found 59 errors in 16 files (checked 1 source file)

$ mypy --scripts-are-modules --ignore-missing-imports params.py  | tail -1
Found 59 errors in 16 files (checked 1 source file)
```

make sure you read the README, it answers your question
