### ISSUE TITLE
Please reopen issue #1 

### ISSUE THREAD

**Issue by phelps-sg** [pre-commit/mirrors-mypy#55]
As per issue #1, I find that when using the pre-commit hook files that are excluded using the exclude directive in mypy.ini are incorrectly included and checked when running mypy as a pre-commit hook.  The same configuration works flawlessly when running mypy.ini stand-alone.  As the OP stated after the issue was closed, they are not relying exclude directives in the pre-commit pipeline, but rather have explicitly configured mypy to exclude the files via mypy configuration options.  

I am using the following in `.pre-commit-config.yaml`:

~~~
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.910'  # Use the sha / tag you want to point at
  hooks:
    - id: mypy
      args: [-v, --no-strict-optional, --ignore-missing-imports, --config-file, mypy.ini]
      additional_dependencies: [ tokenize-rt==3.2.0 ]
~~~

When I run the hook, in the verbose log output I see:

~~~
LOG:  Mypy Version:           0.910
LOG:  Config File:            mypy.ini
LOG:  Configured Executable:  /home/sphelps/.cache/pre-commit/repojp_mrse_/py_env-python3.8/bin/python
LOG:  Current Executable:     /home/sphelps/.cache/pre-commit/repojp_mrse_/py_env-python3.8/bin/python
LOG:  Cache Dir:              .mypy_cache
LOG:  Compiled:               True
LOG:  Exclude:                jupyter/trace.py
~~~

However, the file jupyter/trace.py is still checked, and I obtain an error report for this file later on in the output.

**Comment by asottile** [comment]
the answer is the same as #1, please read my message and notice that you're missing `exclude` in your pre-commit configuration.

**Comment by phelps-sg** [comment]
As with the other posters in #1 I am still confused.  I have tried an exclude directive in the pre-commit configuration as well as in mypy.ini and the file still still gets checked.  Apologies for my stupidity but a full working example would be extremely helpful, not only for me, but also for possibly for similarly algorithmically-challenged users.

**Comment by asottile** [comment]
can you provide a reproducible example? I can fix something that's broken
