### ISSUE TITLE
Pre-commit mypy behaves differently to standalone mypy

### ISSUE THREAD

**Issue by vancromy** [pre-commit/mirrors-mypy#61]
Hello,

I'm encountering the situation in the attached screenshot and I'm not sure whether it is due to user error on my part or some magic in the background:
<img width="915" alt="Screenshot 2021-11-25 at 12 52 30" src="https://user-images.githubusercontent.com/59556820/143437783-d6d0bac2-a86d-4a5d-93f3-ce670f8c074e.png">

pre-commit version:
pre-commit 2.15.0

.pre-commit-config.yaml:
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear]
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML]
        args: [--ignore-missing-imports, --scripts-are-modules]
```
mypy version:
mypy 0.910

The error picked up by the pre-commit mypy refers to a class attribute `df_original` which is inherited from the grandparent class of `Sheardata`. Vscode's mypy & mypy in the CLI do not seem to have a problem with this inherited class attribute but pre-commit's mypy does.

**Comment by asottile** [comment]
without the redacted information I can't help you -- but I'd recommend reading the README which can help you understand the potential differences

**Comment by vancromy** [comment]
The redacted information doesn't really redact anything that would be useful in solving this issue (it's just covering names & filepaths)...

For those interested in knowing what was the cause of the problem (and this may be due to me being new to the pre-commit workflow): 

My committed file depended on some changes to the grandparent class which I hadn't committed yet and my assumption is that pre-commit does not look at the latest version of the code when running its checks but rather only runs its checks against **the committed files and the most recently committed version of all other files**. As such if the changes to your codebase that you are attempting to commit would break in the previously committed version of your codebase, you should expect it to fail in pre-commit's isolated environment. 

So this issue was quite simply related to the order in which I chose to commit my changes...

**Comment by asottile** [comment]
> The redacted information doesn't really redact anything that would be useful in solving this issue (it's just covering names & filepaths)...

it absolutely does, because I have nothing to reproduce -- I can't debug a screenshot but I can debug files on disk and a command to run
