### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by PointerFLY** [pre-commit/mirrors-mypy#70]
Hi, I noticed that `from __future__ import annotation` is added since 0.940 https://github.com/pre-commit/mirrors-mypy/commit/d37f9c4f0c433417baf54659f3e89a5467364668.

The thing is, my local env is still 3.6 and mypy support >=3.6 version as well. 
Adding this makes pre-commit failed to run setup.py because of `from __future__ import annotation` in a 3.6 env. 

Shouldn't we make sure this mirrors-mypy compatible with mypy. I suggests removing it until mypy drops support for 3.6

```
...
     cwd: /home/xxx/.cache/pre-commit/repoi00qvb2m/
Complete output (6 lines):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xxx/.cache/pre-commit/repoi00qvb2m/setup.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by asottile** [comment]
sorry, we only support versions of python which aren't end-of-lifed

**Comment by PointerFLY** [comment]
Understand, I will found another way around, thanks.
