### ISSUE TITLE
pre-release additional dependencies

### ISSUE THREAD

**Issue by Greedquest** [pre-commit/mirrors-mypy#71]
My package depends on a pre-release version of a package:

```
pip install poetry-core --pre
```

How do I specify this in the `additional_dependencies` field of my config?

**Comment by asottile** [comment]
can you show what you've tried? it should just work

**Comment by Greedquest** [comment]
I just tried

```
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.950'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [types-all, GitPython, poetry-core --pre]
```

**Comment by Greedquest** [comment]
@asottile Ah I got it:

https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions

There are 2 ways to install a pre-release

> Starting with v1.4, pip will only install stable versions as specified by [pre-releases](https://www.python.org/dev/peps/pep-0440/#handling-of-pre-releases) by default. If a version cannot be parsed as a compliant [PEP 440](https://peps.python.org/pep-0440/) version then it is assumed to be a pre-release.
> 
> If a Requirement specifier includes a pre-release or development version (e.g. >=0.0.dev0) then pip will allow pre-release and development versions for that requirement. This does not include the != flag.
> 
> The pip install command also supports a [--pre](https://pip.pypa.io/en/stable/cli/pip_install/#install-pre) flag that enables installation of pre-releases and development releases.

So instead of `--pre` I just use `poetry-core>=1.1.0a0` for example
