### ISSUE TITLE
How to depend on local project?

### ISSUE THREAD

**Issue by rdbisme** [pre-commit/mirrors-mypy#76]
I am in a monorepo configuration. I have two projects, `src/a` and `src/b`. `src/b` depends on `src/a`, but when running `mypy` it can't correctly type check `src/b` because it needs `src/a` to be installed. 

Is there a way to specify a local `additional_dependency`?

**Comment by rdbisme** [comment]
Nvm. My problem was that I was missing `py.typed` from a local project to mark it as typed.

**Comment by rdbisme** [comment]
Well, the `py.typed` now is correctly picked up if using `language: system` but still need to install the `src/a` package if using `language:python`. So the question stays! :)

(Sorry for the noise)

**Comment by asottile** [comment]
please search the tracker. there are many duplicates (try "repository under test") and don't skip the issue template next time
