### ISSUE TITLE
Question / request: Can I use `master` (or a specific commit) for mypy?

### ISSUE THREAD

**Issue by GideonBear** [pre-commit/mirrors-mypy#80]
Mypy is currently preparing to release 1.0, not releasing any versions before that. There were quite a few features added which I use in my projects. With this mirror, I unfortunately can't use `master` or a specific commit, just the versions released to PyPI, which means I can't use those features.
I see three solutions:
- [python/mypy](https://github.com/python/mypy) adds a hook, and somehow makes it use wheels (maybe via [mypy_mypyc-wheels](https://github.com/mypyc/mypy_mypyc-wheels))
- [python/mypy](https://github.com/python/mypy) releases pre-releases/dev releases once in a while
- [pre-commit/mirrors-mypy](https://github.com/pre-commit/mirrors-mypy) adds a tag for `master` once in a while (maybe every day or week)

I would completely understand if this is not something you're going to do anything about; 1.0 is releasing soon anyway, but I just wanted to share this with you in case you have a solution or this is something you want to apply to other mirrors as well.

Similar/possibly related issues: #75

**Comment by asottile** [comment]
yeah this is why mirrors are non ideal
