### ISSUE TITLE
Redesign this hook?

### ISSUE THREAD

**Issue by GeorgeHermann** [pre-commit/mirrors-mypy#83]
```python3
# foo.py
foo_val: int = 0
```

```python3
# bar.py
from foo import foo_val
bar_val: int = foo_val + 3
```

Given these two files, if I change `foo_val` from an int to a str, then a type checker would flag this as an error. Given also a reasonable definition of "type checker." Or even a rudimentary one.

Otherwise, why include the whole file? You might as well "type check" only the lines that got changed 😬 

It's perhaps an inconvenient truth. Static type-checking is done at the level of the codebase and not at the level of just the line of text that got changed. The process can be inefficient, which is why part of the type checker's job is to figure out which content can be safely ignored. That's sort of the whole point of the type check: what you do in one place matches up with every other place that depends on it and with every other place on which it depends. A good type checker like mypy optimizes away a lot of the redundant checks, fortunately.

I understand that some people are seemingly [confused](https://github.com/pre-commit/mirrors-mypy/issues/62) on this topic. Presumably, that is because they are familiar at a deep level only with dynamic languages. I realize also that allowing mypy to run with dependencies installed and on every file might not be a minor rewrite.

Doing otherwise leaves us in a weird place though. Anyone expecting reasonable defaults - in contrast to what [this article](https://jaredkhan.com/blog/mypy-pre-commit) diplomatically refers to as "slightly opinionated" defaults - will end up _wasting_ time thanks to mirrors-mypy. At best, unwitting users will catch the implications of the little note in the `README.md` indicating that mypy has been crippled. At worst, they will only realize way down the line that the hook wasn't doing what one would rightly have expected.

If including the dependencies of `requirements.txt` and allowing mypy to check the whole codebase is out of the question, perhaps this mirror should not exist. Developers who use mypy *want* type checking. If they know what that means, they want all the files checked and they want their dependencies installed. If they are naive with respect to how type checking works, all the more reason not to give them something half-baked as the default.

**Comment by asottile** [comment]
please search the issue tracker
