### ISSUE TITLE
Duplicate module

### ISSUE THREAD

**Issue by ZhiyuanChen** [pre-commit/mirrors-mypy#86]
For some reason, Mypy reads a file twice and think they are different module with the same name. 

```
xxx/runner.py: error: Duplicate module named "xxx.runner" (also at "xxx/runner.py")
xxx/runner.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
xxx/runner.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
```

**Comment by asottile** [comment]
show your config

**Comment by ZhiyuanChen** [comment]
> show your config

Sorry


default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/PSF/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [--profile, black]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 0.12.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
        files: chanfig
        additional_dependencies:
          - types-PyYaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        files: chanfig
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        files: chanfig
      - id: debug-statements
      - id: end-of-file-fixer
        files: chanfig
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

**Comment by asottile** [comment]
seems to be passing for me https://results.pre-commit.ci/run/github/488542508/1687847944.SUBTBI8pSh6xFPcCnC5fvA

**Comment by ZhiyuanChen** [comment]
> seems to be passing for me https://results.pre-commit.ci/run/github/488542508/1687847944.SUBTBI8pSh6xFPcCnC5fvA

Yes, it’s very strange. 
I use this config for multiple projects and only one of them are complaining.

**Comment by asottile** [comment]
well it can't be the exact config because that config above contains a project name

show your *actual* configuration and *actual* output or I can't help you

**Comment by ZhiyuanChen** [comment]
> well it can't be the exact config because that config above contains a project name
> 
> show your _actual_ configuration and _actual_ output or I can't help you

The actual configuration is listed below:

```ymal
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/PSF/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [--profile, black]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 0.12.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        args: [--ignore-words=.codespell-whitelist.txt]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        files: deepprotein
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
```

**Comment by Stoops-ML** [comment]
1. Does this occur for mypy rev: v1.4.1?
2. Does running mypy locally on the folders/files produce the same results?

**Comment by ZhiyuanChen** [comment]
> 1. Does this occur for mypy rev: v1.4.1?

Sorry, I have resolved this issue, see below. 

> 2. Does running mypy locally on the folders/files produce the same results?

Run Mypy locally produced a similar results that module is duplicated under `builds`
I solved this issue by removing builds directory.

**Comment by ZhiyuanChen** [comment]
@asottile I think the inconsistent behaviour between mypy and mypy hook is still an issue. The path in the output is wrong.

**Comment by asottile** [comment]
this literally just runs `mypy your files here` so it can't be

**Comment by ZhiyuanChen** [comment]
> this literally just runs `mypy your files here` so it can't be

But it just happened. 

pre-commit:
```
package/inference.py: error: Duplicate module named "package.inference" (also at "package/inference.py")
package/inference.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
package/inference.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
```

Mypy
```
package/__init__.py: error: Duplicate module named "package" (also at "./build/lib/package/__init__.py")
package/__init__.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
package/__init__.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
```
