### ISSUE TITLE
Action bot did not make a 1.5.0 mirror

### ISSUE THREAD

**Issue by pechersky** [pre-commit/mirrors-mypy#87]
mypy 1.5.0 was released on July 22, 2023
https://github.com/python/mypy/releases/tag/v1.5.0

The mirroring bot jobs subsequent to this (e.g. July 23, July 24th) didn't pick this up
https://github.com/pre-commit/mirrors-mypy/actions/runs/5635434885/job/15266421418#step:7:2
https://github.com/pre-commit/mirrors-mypy/actions/runs/5642612964/job/15282804595#step:7:2

Running the action locally does pick it up:
```
$ git clone https://github.com/pre-commit/mirrors-mypy.git
$ cd mirrors-mypy
$ pre-commit-mirror . --language=python --package-name=mypy --types-or=python --types-or=pyi --args=--ignore-missing-imports,--scripts-are-modules --require-serial
[main 94ee101] Mirror: 1.5.0
 2 files changed, 2 insertions(+), 2 deletions(-)
$ git show --summary
commit 94ee101acce0b3b6db3d055a2d0bb508c7a7757d (HEAD -> main, tag: v1.5.0)
Author: Yakov Pechersky <REDACTED>
Date:   Thu Aug 10 21:03:36 2023 -0400

    Mirror: 1.5.0
```

**Comment by asottile** [comment]
it was released today. please be patient
